### ISSUE TITLE
Is there a way to prevent rounding?

### ISSUE THREAD

**Issue by Genarito** [vi/float-pretty-print#1]
Hi!

First of all, congratulation on this amazing crate. I'd like to know if there's a way to prevent rounding for big numbers. For instance:

```rust
use float_pretty_print::PrettyPrintFloat;

fn main() {
    println!("{}", PrettyPrintFloat(224617.445991228));
}
```

Prints `2.24617446e5` which, in my case, breaks some tests those expect getting the exact value `224617.445991228`.

Could it be possible with your crate?

**Comment by vi** [comment]
What do you mean by "exact value"?

`224617.445991228f64 != 224617 + 445991228 / 1000000000`

Default float printing algorithm may be smart to balance compactness and precision, but if you specify precision it will show the discrepancy between input float and output representation:

`println!("{:.30}", 224617.445991228f64);` -> `224617.445991228014463558793067932129`

And float-pretty-print's main job is to be predictable with minimal and maximal width, e.g. for formatting numbers into tables. It also prefers using exponential form starting from 5 digits because of that's supposedly more readable for users.

If using string representation of floats in tests is a good idea at all, then those tests should also be generated with FloatPrettyPrint using the same settings.

**Comment by Genarito** [comment]
HI! Thank you for your quick response!

When I say "exact value" I mean no loss of precision. When I found this crate I was looking for a way to display a floating value in a shorter way, but without losing decimals. I find it good that a value like `50000000000` is represented as `5e10`, but I would like values that cannot be represented in scientific notation without losing precision directly to be represented in the same way as `format!` would do. Check the following example:

```rust
use float_pretty_print::PrettyPrintFloat;

fn main() {
    let original = 224617.445991228;
    let without_pretty = format!("{}", original);
    let with_pretty = format!("{}", PrettyPrintFloat(original));

    // This works
    assert_eq!(
        without_pretty.parse::<f64>().unwrap(),
        original
    );
    
    // This does not work
    assert_eq!(
        without_pretty.parse::<f64>().unwrap(),
        with_pretty.parse::<f64>().unwrap()
    );

    // This one does not work either
    assert_eq!(
        with_pretty.parse::<f64>().unwrap(),
        original
    );
}
```

**Comment by vi** [comment]
Such mode wouldn't have guaranteed minimum/maximum width.

Do you think this use case is common enough to warrant inclusion into the library?

 For now you can just use some workaround like this:

```rust
use float_pretty_print::PrettyPrintFloat;

pub struct PrettyPrintFloatWithFallback(pub f64);

impl std::fmt::Display for PrettyPrintFloatWithFallback {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error> { 
        let w = f.width().unwrap_or(3);
        let p = f.precision().unwrap_or(12);
        let tmp = format!("{:w$.p$}", PrettyPrintFloat(self.0), w=w, p=p);
        let parseback : Result<f64,_> = tmp.parse();
        match parseback {
            Ok(x) if x == self.0 => tmp.fmt(f),
            _ => self.0.fmt(f),
        }
    }
}

fn main() {
    println!("{}", PrettyPrintFloatWithFallback(224617.445991228));
}
```

**Comment by vi** [comment]
Also `assert_eq` should not be used on float in general. There are crates for approximate equality assertions.

Exactly comparing floats should be avoided. And for special needs there is `to_bits()` to show that you are really interested that all underlying bits are the same.

**Comment by Genarito** [comment]
Cool! Thanks for your solution. I don't know if it will be a common case, but I see that it can be useful when you want to use the crate for another purpose than debugging values quickly, in the end, it's your decision, in my case the solution you wrote works for me! :D

**Comment by vi** [comment]
> solution you wrote works for me

I'm not sure it is much different compared to just formatting the floats directly without using the library at all.

**Comment by Genarito** [comment]
It's totally different. In my case, just to make an example, I'm writing a library that parses and emits text in a specific format. When users use values like `5e22` in the parsing process I get the float value, but when I emit the same value I'm currently getting `50000000000000000000000`, with your crate I'll get `5e22`. But users can use arbitrary float values, so I need the exact representation, if I just use `format!` I always get the larger representation. That's why your crate is very useful to me, but I can't lose precision as users want to get the same value they wrote.
