### ISSUE TITLE
Minimum width not correct

### ISSUE THREAD

**Issue by PvdBerg1998** [vi/float-pretty-print#2]
Negative exponents seem to miscalculate the minimum width. Example: 
```rust
format!("= {:6.6}", PrettyPrintFloat(5.0e-50))
```
results in `5e-50`. This is 5 characters wide while the minimum is 6. I am expecting it to print `_5e-50` in this case, with the underscore indicating a space for visibility.

**Comment by PvdBerg1998** [comment]
Update: changing to an odd minimum width seems to fix the issue. I suspect it's related to not printing a dot combined with a decimal. Going from `5e-50` to `5.0e-50` adds two characters which keeps the length odd.

**Comment by PvdBerg1998** [comment]
Another update: `100 cos(3 deg) = 99.86295` is also printing at the wrong width with the minimum width set to 9. Changing to 30 degrees correctly pads the result, while small angles result in 8 characters.

**Comment by vi** [comment]
Do you maybe have a comprehensive test suite for `float-pretty-print`'s correctness?

**Comment by vi** [comment]
The mistake is also present in tests: https://github.com/vi/float-pretty-print/blob/master/src/test.rs#L4287

**Comment by vi** [comment]
Fixed and published v0.1.1.
